# extract strings - most are used in both checker script and installer script
check_brew="command -v brew >/dev/null 2>&1"
check_git="command -v git >/dev/null 2>&1 && git version | grep -q 'git version'"
check_git_user="command -v git >/dev/null 2>&1 && git config --list | grep -q 'github.user='"
check_git_email="command -v git >/dev/null 2>&1 && git config --list | grep -q 'github.email='"
check_brew_gmp="command -v brew >/dev/null 2>&1 && brew list | grep -q 'gmp'"
check_brew_gnupg="command -v brew >/dev/null 2>&1 && brew list | grep -q 'gnupg'"
check_rvm="command -v rvm >/dev/null 2>&1 && which rvm | grep -q '/Users/.*/\.rvm/bin/rvm'"
check_ruby_version="command -v rvm >/dev/null 2>&1 && rvm list | grep -Fq '=* ruby-2.6.0 [ x86_64 ]'"
check_rvm="command -v rvm >/dev/null 2>&1 && rvm list | grep -Fqv 'Warning! PATH'"
check_learn="command -v gem >/dev/null 2>&1 && gem list | grep -q 'learn-co'"
check_bundler="command -v gem >/dev/null 2>&1 && gem list | grep -q 'bundler'"
check_cask="! brew info cask &>/dev/null"
check_atom="command -v atom >/dev/null 2>&1 && atom -v | grep -q 'Atom'"
check_atom_editor="cat ~/.learn-config | grep ':editor:' | grep -q 'atom'"
check_nokogiri="command -v gem >/dev/null 2>&1 && gem list | grep -q 'nokogiri'"
check_sqlite3="command -v sqlite3 >/dev/null 2>&1"
check_postgres="command -v postgres >/dev/null 2>&1 && postgres --version | grep -q 'postgres (PostgreSQL)'"
check_psql="command -v psql >/dev/null 2>&1 && psql --version | grep -q 'psql (PostgreSQL)'"
check_rails="command -v rails >/dev/null 2>&1 && rails --version | grep -q 'Rails'"
check_rails_gem="command -v gem >/dev/null 2>&1 && gem list | grep -q 'rails'"
check_nvm="command -v nvm >/dev/null 2>&1 && nvm --version | grep -q '[0-9]*\.[0-9]*\.[0-9]*'"
check_node="command -v node | grep -q '/Users/.*/.nvm/versions/node/v.*/bin/node'"
check_chrome="[ -f /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome ] && /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | grep -q 'Google Chrome'"
check_slack="[ -f /Applications/Slack.app/Contents/MacOS/Slack ] && /Applications/Slack.app/Contents/MacOS/Slack --version | grep -q ''"
check_git_user_config="command -v git >/dev/null 2>&1 && git config github.user"
check_git_email_config="command -v git >/dev/null 2>&1 && git config github.email"
check_learn_name="command -v learn >/dev/null 2>&1 && learn whoami | grep 'Name:' | sed 's/Name://g' | sed -e 's/^[[:space:]]*//'"
check_learn_username="command -v learn >/dev/null 2>&1 && learn whoami | grep 'Username:' | sed 's/Username://g' | sed -e 's/^[[:space:]]*//'"
check_learn_email="command -v learn >/dev/null 2>&1 && learn whoami | grep 'Email:' | sed 's/Email://g' | sed -e 's/^[[:space:]]*//'"
